name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install mock>=1.0.1
        pip install tox>=2.3.1
    - name: Run test suite with tox
      run: |
        tox
